<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>Axiom.Cosmos.Model</AssemblyName>
		<RootNamespace>Axiom.Cosmos.Model</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\GeoMath\GeoMath.csproj" />
	  <ProjectReference Include="..\GeoShape\GeoShape.csproj" />
	  <ProjectReference Include="..\Physics\Physics.csproj" />
	</ItemGroup>

</Project>
